vm_core:
    resource: "@VMCoreBundle/Resources/config/routing.yml"
    prefix:   /

vm_administrateur:
    resource: "@VMAdministrateurBundle/Resources/config/routing.yml"
    prefix:   /

vm_client:
    resource: "@VMClientBundle/Resources/config/routing.yml"
    prefix:   /

vm_prestataire:
    resource: "@VMPrestataireBundle/Resources/config/routing.yml"
    prefix:   /

vm_salarie:
    resource: "@VMSalarieBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: VMCoreBundle:Default:index

login_check:
    path: /login_check

logout:
    path: /logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
