# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    VM\CoreBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_CLIENT:      ROLE_CLIENT
    ROLE_PRESTATAIRE: ROLE_PRESTATAIRE
    ROLE_SALARIE:     ROLE_SALARIE
    ROLE_ADMIN:       ROLE_ADMIN
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    VM\CoreBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:      ^/
      anonymous:    true
      provider:     main
      form_login:
        check_path: login_check
      logout:
        path:       logout
        target:     /
  access_control:
        - { path: ^/salarie, roles: ROLE_SALARIE }
        - { path: ^/prestataire, roles: ROLE_PRESTATAIRE }
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
